### ISSUE TITLE
Publish latest version to Maven Central (not only *plugin*)

### ISSUE THREAD

**Issue by salomvary** [ricksbrown/cowsay#13]
I'm trying to use this very important piece of software as a Maven dependency but `1.0.3` is [only published as Maven plugin, not as a standalone module](https://search.maven.org/#artifactdetails%7Ccom.github.ricksbrown%7Ccowsay%7C1.0.3%7Cmaven-plugin).

Thanks!

**Comment by ricksbrown** [comment]
Hi @salomvary. Thanks for raising this issue and in particular recognising the importance of this important software 🐮   I am sure this is a showstopper for your project 😁 and hope I have responded quickly enough to prevent serious delays 😆 

I added [a new "download" section](https://github.com/ricksbrown/cowsay#download) to the readme which may hopefully clarify the matter...? 
In short, the JAR on Maven is an "all-in-one", it is even executable. 

Good luck and thanks again  ✨ I hope you enjoy the tool. 

Please let me know if I have misunderstood the issue you are facing and I'm sure we can find the answer.

**Comment by salomvary** [comment]
```
 __________________________________________
/ OK, will use one of the newly documented \
| ways.                                    |
\ Thanks!                                 /
 ------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
