### ISSUE TITLE
Distinct name?

### ISSUE THREAD

**Issue by apjanke** [ricksbrown/cowsay#3]
Any chance of renaming this project to "jcowsay" or something similar, to distinguish it from the original cowsay project?

Also so forks on GitHub have distinct names. There are a couple other "somebody/cowsay" repos out there with implementations in other languages. Would be nice to be able to fork multiple implementations and have the repo names be distinct and still match the upstream repos. For example, I forked [sckott/cowsay](https://github.com/sckott/cowsay) and this repo, and one of them ended up being `apjanke/cowsay-1`, which is kind of lame.

**Comment by ricksbrown** [comment]
Hi @apjanke. I've been thinking about this for a while.

I think ultimately you are correct, it would be nice if I had thought of it and named it `jcowsay`.

On the other hand I'm sure you will agree that the vast majority of users are not affected by this issue. It affects only those people who clone multiple implementations of cowsay on github.

This is further mitigated by the fact that you are able to rename the "cowsay-1" repository to something more meaningful by your repository "Edit" button and give it a more meaningful name (like `java-cowsay`).

Anyways thanks for raising the idea and I hope you enjoy the java port.

**Comment by apjanke** [comment]
Yeah, it's just a convenience thing for a small number of users. No big dieal.
