### ISSUE TITLE
Tests failing on my machine

### ISSUE THREAD

**Issue by LyndonGingerich** [ricksbrown/cowsay#44]
```
$ java --version
openjdk 21.0.5 2024-10-15
OpenJDK Runtime Environment (build 21.0.5+11-Ubuntu-1ubuntu124.04)
OpenJDK 64-Bit Server VM (build 21.0.5+11-Ubuntu-1ubuntu124.04, mixed mode, sharing)
```

Many of the tests are failing for me; the test code returns an empty string instead of the expected cow. As an example, `testSetMessage` in `CowExecutorTest` is failing this way. The deepest I could chase the running code before it ran into framework code was `Cowloader.getCowFromResources` with a `cowName` of `default.cow`. It returns `null`. (It was called from `Cowloader.load`, line 87.)

Is there something odd about my setup? Am I doing something wrong? I'm new to the JVM.

**Comment by LyndonGingerich** [comment]
Workflow stack trace to avoid XY problems:
1. I want the tests passing so that I can write new tests.
2. I want to write a test to confirm a disparity between the behaviors of `CowExecutor` and of the official Cowsay utility.
3. I want to ensure correct behavior because the official utility seems to allow specifying both a cowfile and a face mode, whereas `CowExecutor` seems to set only the face mode when both are specified.
4. I want both the face and the cowfile because I am writing a random cow generator in Kotlin.
5. I am writing a random cow generator in Kotlin as the first iteration of a Cowsay mobile app for the sheer joy of having published something.

The reason `Cowloader.getCowFromResources` was called was that `cowEnvironment.getVariable("COWPATH")` in `Cowloader.getCowFromCowPath` returned `null`. This is odd since I have Cowsay installed on my machine, but convenient for me since I want to know quickly if my program doesn't work without having Cowsay preinstalled.

Oh yes, I forgot to include my version information.
```kts
implementation("com.github.ricksbrown:cowsay:1.1.0:lib")
```

**Comment by LyndonGingerich** [comment]
I haven't heard back, so I'm going to assume that the tests should not be failing and attempt to repair them unless otherwise directed.

**Comment by LyndonGingerich** [comment]
Actually, skip that. I don't need those tests.

**Comment by LyndonGingerich** [comment]
Disregard that. `CowsayTests` is failing as well. I need those.

**Comment by LyndonGingerich** [comment]
I figured it out. Running the tests directly in Rider doesn't work. Running `mvn test` does.

**Comment by ricksbrown** [comment]
Sorry I was away and missed all of this.
Thanks for the info, sounds like you got it working in the end...
